      "AWS::CloudFormation::Interface":{
         "ParameterGroups":[
            {
               "Label":{
                  "default":"Network Configuration"
               },
               "Parameters":[
                  "createVPCDevelopment",
                  "createVPCManagement",
                  "pProductionVPCName",
                  "pDevelopmentVPCName",
                  "pManagementVPCName",
                  "pProductionCIDR",
                  "pDevelopmentCIDR",
                  "pManagementCIDR",
                  "pAppPrivateSubnetACIDR",
                  "pAppPrivateSubnetBCIDR",
                  "pDMZSubnetACIDR",
                  "pDMZSubnetBCIDR",
                  "pDBPrivateSubnetACIDR",
                  "pDBPrivateSubnetBCIDR",
                  "pDMZSubnetBCIDR",
                  "pDevSubnetACIDR",
                  "pDevSubnetBCIDR",
                  "pManagementSubnetACIDR",
                  "pManagementSubnetBCIDR",
                  "pNatInstanceType"
               ]
            },
            {
               "Label":{
                  "default":"EC2 Configuration"
               },
               "Parameters":[
                  "pAppInstanceType",
                  "pWebInstanceType",
                  "pAppAmi",
                  "pWebServerAMI",
                  "pKeyName"
               ]
            },
            {
               "Label":{
                  "default":"Logging"
               },
               "Parameters":[
                  "pCreateCloudTrail",
                  "pS3CloudTrailLocal",
                  "pS3CloudTrailBucketExisting"
               ]
            },
            {
               "Label":{
                  "default":"Database"
               },
               "Parameters":[
                  "pDBClass",
                  "pDBAllocatedStorage",
                  "pDBName",
                  "pDBUser",
                  "pDBPassword"
               ]
            },
            {
               "Label":{
                  "default":"Optional Buckets"
               },
               "Parameters":[
                  "pBackupBucketName",
                  "pAppLogsBucketName",
                  "pWebContentBucketName"
               ]
            },
            {
               "Label":{
                  "default":"Nested StackURLs"
               },
               "Parameters":[
                  "stack1URL",
                  "stack2URL",
                  "stack3URL",
                  "stack4URL"
               ]
            }
         ],
         "ParameterLabels":{
            "pCreateCloudTrail":{
               "default":"Do you want to enable CloudTrail Logging?"
            },
            "pS3CloudTrailBucketExisting":{
               "default":"Specify an existing bucket name if one already exists"
            },
            "pS3CloudTrailLocal":{
               "default":"Specify a new bucket name to create for CloudTrail"
            },
            "createVPCDevelopment":{
               "default":"Do you want to create a Development VPC in this account?"
            },
            "createVPCManagement":{
               "default":"Do you want to create a Management VPC in this account?"
            }
         }
      },
      "Stack":{
         "Value":"0"
      },
      "VersionDate":{
         "Value":"09292015"
      },
      "Identifier":{
         "Value":"main-webapp-linux-01"
      },
      "Input":{
         "Description":"Input of all required parameters in nested stacks"
      },
      "Output":{
         "Description":"N/A"
      }
